First version, export study summaries
EBIvariation/eva-omicsdi-export pull request #1
Opened 2017-05-03 14:37 UTC by pabarcgar

2017-05-04 14:32 UTC, cyenyxe requested changes

2017-05-04 14:32 UTC, cyenyxe commented on pom.xml
> +  <build>
Keep the POM structure similar to that in other projects (dependencies before build plugins).

2017-05-04 14:32 UTC, cyenyxe commented on pom.xml
> +  <artifactId>bd2k-ddi-exporter</artifactId>
omicsdi-exporter

2017-05-04 14:32 UTC, cyenyxe commented on pom.xml
> +  <repositories>
Add EVA artifact repositories.

2017-05-04 14:32 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/StudyExporterAppl.java
> +package uk.ac.ebi.eva.bd2k;
License and copyright in source files.

2017-05-04 14:32 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/StudyExporterAppl.java
> +public class StudyExporterAppl {
I'm not sure about not using Spring Boot for 2 reasons:

* It parses and merges arguments provided via properties files and CLI
* It can read properties files from inside and outside the JAR file, which facilitates deployment in multiple environments without recompiling

2017-05-04 14:32 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/client/StudyEvaWSClient.java
> +public class StudyEvaWSClient implements StudyClient {
Add blank line after class header.

2017-05-04 14:32 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/export/StudyExporter.java
> +        database.setRelease("BETA");
We could use `LocalDate.now()` too, as we don't have release numbers.

2017-05-04 14:32 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/export/StudyExporter.java
> +    public StudyExporter(StudyClient studyClient, StudyTransformer transformer, OmicsDataMarshaller marshaller, String outputDirectory) {
The exporter could be constructed using only the `StudyTransformer` and `OmicsDataMarshaller`, because those define its behaviour. Then a list of `VariantStudy` objects and an output directory could be the arguments of the `export()` method, because those define an "export run".

This will reduce coupling and simplify testing, because studies can be provided directly and it will be no longer necessary to reference `StudyClient` from this class.

2017-05-04 14:32 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/export/StudyExporter.java
> +package uk.ac.ebi.eva.bd2k.export;
A package for this single class, and another one for `StudyTransformer` and `StudyTransformerImpl` seems a bit too much. Maybe they could all be put together in this package, and reorganized if the project grows a lot in the future?

2017-05-12 18:24 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/export/StudyTransformerImpl.java
> +import uk.ac.ebi.eva.bd2k.export.StudyTransformer;
This import should not be necessary after the package renaming.

2017-05-17 10:16 UTC, pabarcgar commented on src/main/java/uk/ac/ebi/eva/bd2k/StudyExporterAppl.java
> +package uk.ac.ebi.eva.bd2k;
this is solved

2017-05-17 10:16 UTC, pabarcgar commented on src/main/java/uk/ac/ebi/eva/bd2k/client/StudyEvaWSClient.java
> +public class StudyEvaWSClient implements StudyClient {
Solved

2017-05-17 10:16 UTC, pabarcgar commented on src/main/java/uk/ac/ebi/eva/bd2k/export/StudyExporter.java
> +package uk.ac.ebi.eva.bd2k.export;
Solved

2017-05-17 13:34 UTC, pabarcgar commented on src/main/java/uk/ac/ebi/eva/bd2k/export/StudyExporter.java
> +        database.setRelease("BETA");
I've done this change in 40e1a00, but now we have some redundancy in the produced XML:

```<database>
  <name>EVA</name>
  <release>2017-05-17</release>
  <release_date>2017-05-17</release_date>
  <entries>
      ...
```
Both elements are mandatory according to the specification, so if we don't have another release value candidate, we can leave it like this.

2017-05-22 13:45 UTC, cyenyxe requested changes

2017-05-22 13:45 UTC, cyenyxe commented on pom.xml
> +    </dependency>
Is this dependency necessary only for `QueryResponse` and `QueryResult`? Wouldn't it be enough to declare `datastore` directly for a more lightweight executable?

2017-05-22 13:45 UTC, cyenyxe commented on pom.xml
> +    </dependency>
This doesn't seem necessary.

2017-05-22 13:45 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/client/StudyEvaWSClient.java
> +            logger.info("Retrieving all EVA studies from {} ...", studyWsUrl);
Not sure how necessary is to mention EVA in all the logging messages when it is an EVA-only application.

2017-05-22 13:45 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/conf/ExporterConfigurationProperties.java
> +@ConfigurationProperties(prefix = "bd2k")
"omicsdi"? "bd2k" is a grant and not a project, so it could be a conflicting namespace for declaring properties.

2017-05-22 13:45 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/export/StudyExporter.java
> +        logger.info("Done");
I would move this inside the try block, so there is confusion when the error and the "done" messages are displayed in the same run.

2017-05-22 13:45 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/client/StudyClient.java
> +public interface StudyClient {
Add class-level documentation, and a blank line after the class header. Applies to the rest of classes/interfaces.

2017-05-22 13:45 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/export/EvaStudyExporter.java
> +        return outputDirectory + "/" + study.getId() + ".xml";
Maybe we should use the files/paths core Java API to ensure the path can be resolved.

2017-05-22 13:45 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/model/VariantStudy.java
> +    public VariantStudy() {
This class must have `hashCode` and `equals` methods declared in order to be used in map data structures correctly.

2017-05-22 13:45 UTC, cyenyxe commented on src/main/resources/application.properties
> +#
Properties files are not code and thus do not need a copyright declaration.

2017-05-22 13:45 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/eva/bd2k/client/StudyEvaWSClientTest.java
> +        // TODO: test other fields
Test them then 😉

2017-05-22 13:45 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/eva/bd2k/export/EvaStudyExporterTest.java
> +                          any(OutputStream.class));
This block looks like mock initialization? If that is the case, then it should be placed in the `setUp()` method.

2017-05-22 13:45 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/eva/bd2k/transform/StudyTransformerTest.java
> +public class StudyTransformerTest {
Add blank line after class header.

2017-05-30 14:23 UTC, pabarcgar commented on src/main/java/uk/ac/ebi/eva/bd2k/model/VariantStudy.java
> +    public VariantStudy() {
Done

2017-05-30 14:23 UTC, pabarcgar commented on src/test/java/uk/ac/ebi/eva/bd2k/transform/StudyTransformerTest.java
> +public class StudyTransformerTest {
Done

2017-05-30 14:27 UTC, pabarcgar commented on src/test/java/uk/ac/ebi/eva/bd2k/export/EvaStudyExporterTest.java
> +                          any(OutputStream.class));
Those are not input "Stubbing" calls, they are verifications that are tied to a particular test (check that this method in this class has been called X times using those parameters) and don't work if we move them to the setup method

2017-05-30 15:09 UTC, cyenyxe reviewed
Just a couple of suggestions to make the documentation a bit clearer.

2017-05-30 15:09 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/export/EvaStudyTransformer.java
> + * EVA Studies omicsDI transformer
Transforms EVA study objects into Database objects from the OmicsDI model.

2017-05-30 15:09 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/export/EvaStudyExporter.java
> + * EVA Studies omicsDI exporter
Exports EVA studies into a format compatible with OmicsDI.

2017-05-30 15:26 UTC, cyenyxe approved these changes

2017-05-30 15:27 UTC, merged