EVA-744 Added publication date
EBIvariation/eva-omicsdi-export pull request #2
Opened 2017-06-02 15:13 UTC by pabarcgar

2017-06-06 10:40 UTC, tomdcsmith requested changes

2017-06-06 10:40 UTC, tomdcsmith commented on src/test/java/uk/ac/ebi/eva/bd2k/client/ProjectEnaWSClientTest.java
> +        ProjectEnaWSClient enaProjectWSClient = new ProjectEnaWSClient(PROJECT_WS_URL, restTemplate);
Could this initialisation be moved to setUp, since a ProjectEnaWSClient with the same configuration is used in both tests?

2017-06-06 10:40 UTC, tomdcsmith commented on src/main/java/uk/ac/ebi/eva/bd2k/client/ProjectEnaWSClient.java
> +    private String getPublicationDate(ProjectType project) {
Maybe I'm not clear on what is going on here, but the ProjectType interface contains a method getFirstPublic, why can this not be used?

2017-06-06 10:40 UTC, tomdcsmith commented on src/test/java/uk/ac/ebi/eva/bd2k/export/EvaStudyExporterTest.java
> +        enaProjectClientMock = sudyId -> new EnaProject(sudyId, "2017-01-01");
"studyId"

2017-06-06 10:40 UTC, tomdcsmith commented on src/test/java/uk/ac/ebi/eva/bd2k/transform/StudyTransformerTest.java
> +        variantStudy = new VariantStudy(studyId, studyName, studyDescription, center, speciesScientificName, projectUrl,
type can be moved to same line as platform

2017-06-07 17:55 UTC, pabarcgar commented on src/main/java/uk/ac/ebi/eva/bd2k/client/ProjectEnaWSClient.java
> +    private String getPublicationDate(ProjectType project) {
You are right, I had not seen that method.

2017-06-07 18:02 UTC, pabarcgar commented on src/main/java/uk/ac/ebi/eva/bd2k/client/ProjectEnaWSClient.java
> +    private String getPublicationDate(ProjectType project) {
changed in 	dcc076a

2017-06-08 08:48 UTC, tomdcsmith approved these changes

2017-06-09 08:09 UTC, cyenyxe requested changes

2017-06-09 08:09 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/client/ProjectClient.java
> +public interface ProjectClient {
Blank line after class header.

2017-06-09 08:09 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/client/ProjectHttpMessageConverter.java
> +public class ProjectHttpMessageConverter implements HttpMessageConverter<ProjectType> {
Blank line after class header.

2017-06-09 08:09 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/client/ProjectHttpMessageConverter.java
> + * HttpMessageConverter that extract a ENA ProjctType object from a XML document
extracts, ProjectType

2017-06-09 08:09 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/export/EvaStudyTransformer.java
> +        entry.addDate(new Date(PUBLICATION_DATE_TAG, getPublicationDate(variantStudy)));
This fields has a "_TAG" suffix. Is it structure any different from the others? Otherwise the suffix should be removed from it or added to all of them for consistency.

2017-06-09 08:09 UTC, cyenyxe commented on src/main/java/uk/ac/ebi/eva/bd2k/client/ProjectEnaWSClient.java
> +        return simpleDateFormat.format(project.getFirstPublic().getTime());
Do we need to return the time or just the date is enough? Disclaimer: I don't know if the ENA API supports it.

2017-06-09 08:09 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/eva/bd2k/client/ProjectEnaWSClientTest.java
> +                Paths.get(this.getClass().getResource("/projectWSResponse.xml").toURI())).stream()
In these kind of files we normally use dashes, as in `project-ws-response.xml`.

2017-06-09 08:09 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/eva/bd2k/client/ProjectEnaWSClientTest.java
> +    private RestTemplate restTemplate;
Declare variables after constants.

2017-06-09 08:09 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/eva/bd2k/client/ProjectEnaWSClientTest.java
> +        String xmlTestFileBody = Files.readAllLines(
Could the file be read just once (`@BeforeClass`)?

2017-06-09 08:09 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/eva/bd2k/client/ProjectEnaWSClientTest.java
> +        assertEquals("GEUVADIS: Genetic European Variation in Disease (http://www.geuvadis.org), is a European Medical Sequencing Consortium aiming at sharing capacity across Europe in high-throughpu
Run the auto-format to ensure long strings are split in multiple lines.

2017-06-09 08:09 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/eva/bd2k/client/ProjectEnaWSClientTest.java
> +                xRef -> xRef.getDB().equals("ENA-SUBMISSION") && xRef.getID().equals("ERA298142")));
Inconsistent indentation, although I like this line more than the other 3.

2017-06-09 08:09 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/eva/bd2k/export/EvaStudyExporterTest.java
>      private static final String STUDY_2_ID = "s2";
Constants before instance variables.

2017-06-09 08:09 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/eva/bd2k/transform/StudyTransformerTest.java
> +    private String studyId;
Instead of making all the following attributes, use `variantStudy` to access them in the asserts.

2017-06-09 08:09 UTC, cyenyxe commented on src/test/java/uk/ac/ebi/eva/bd2k/transform/StudyTransformerTest.java
> +    public void transformProjectWithOldPublicationDate() throws Exception {
Make more clear that this test only checks the date. `transform` vs `transformProjectWithOldPublicationDate` sounds like both test everything. Maybe something like `testNoDatePreviousToEvaIsUsed`?

2017-06-09 13:24 UTC, pabarcgar commented on src/main/java/uk/ac/ebi/eva/bd2k/client/ProjectEnaWSClient.java
> +        return simpleDateFormat.format(project.getFirstPublic().getTime());
ENA Project WS returns just the date, with no time

2017-06-09 14:21 UTC, cyenyxe approved these changes

2017-06-09 14:21 UTC, merged